<a href="https://colab.research.google.com/github/poolaNaveen/Python/blob/main/numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
data=np.random.randint(0,10,(3,3))
data

array([[0, 1, 1],
       [1, 2, 7],
       [2, 6, 8]])

In [ ]:
import numpy as np
data=np.random.randint(0,20,(4,4))
data

array([[ 6,  1,  8, 13],
       [ 0,  3,  8,  1],
       [14,  6,  7, 12],
       [16,  8,  2, 15]])

In [ ]:
import numpy as np
data=np.random.randint(0,30,(4,4))
data

array([[23, 25,  6, 23],
       [21, 20, 24, 17],
       [19, 23, 17,  7],
       [ 6,  0,  5, 11]])

In [ ]:
np.random.randint(0,10,(2,2))kk

array([[6, 5],
       [4, 5]])

In [ ]:
import numpy as np
data = np.random.randint(0,5,(3,3))
data
data.sum(axis=1)

array([6, 7, 4])

In [ ]:
data.sum(axis=1)

array([3, 8, 4])

In [ ]:
import numpy as np
data = np.random.randint(0,20,(3,3))
data


array([[12, 10, 15],
       [19,  7,  5],
       [ 4, 19,  4]])

In [ ]:
data.sum(axis=1)


array([37, 31, 27])

In [ ]:
data.max(axis=1)

array([15, 19, 19])

In [ ]:
data.min(axis=0)

array([4, 7, 4])

In [ ]:
data = np.random.randint(0,10,10)
data

array([0, 9, 9, 0, 6, 6, 5, 3, 8, 4])

In [ ]:
data = np.random.randint(0,10,10)
data


array([1, 4, 0, 9, 2, 9, 7, 4, 0, 9])

In [ ]:
data.argmin()

np.int64(2)

In [ ]:
data = np.random.randint(0,100,(3,3))
data.argmin(axis=1)
data


array([[45, 97, 35],
       [26, 61, 78],
       [ 5, 38, 27]])

In [ ]:
data.argmin(axis=1)


array([2, 0, 0])

In [ ]:
# Define column names
columns = [
    "OrderID", "Date", "CustomerName", "Product", "Category",
    "Quantity", "Price", "Discount", "Sales", "TotalAmount", "PaymentMode"
]




data = np.array([
    [1001, "2025-10-01", "Naveen P", "Laptop", "Electronics", 1, 55000, "5%", 55000, 52250, "Credit Card"],
    [1002, "2025-10-01", "Raju K", "T-Shirt", "Apparel", 3, 600, "0%", 1800, 1800, "UPI"],
    [1003, "2025-10-02", "Manju R", "Refrigerator", "Appliances", 1, 32000, "10%", 32000, 28800, "Debit Card"],
    [1004, "2025-10-02", "Ravi S", "Shoes", "Footwear", 2, 2500, "15%", 5000, 4250, "Cash"],
    [1005, "2025-10-03", "Ryou M", "Mobile Phone", "Electronics", 1, 22000, "8%", 22000, 20240, "Net Banking"]
], dtype=object)
data

array([[1001, '2025-10-01', 'Naveen P', 'Laptop', 'Electronics', 1,
        55000, '5%', 55000, 52250, 'Credit Card'],
       [1002, '2025-10-01', 'Raju K', 'T-Shirt', 'Apparel', 3, 600, '0%',
        1800, 1800, 'UPI'],
       [1003, '2025-10-02', 'Manju R', 'Refrigerator', 'Appliances', 1,
        32000, '10%', 32000, 28800, 'Debit Card'],
       [1004, '2025-10-02', 'Ravi S', 'Shoes', 'Footwear', 2, 2500,
        '15%', 5000, 4250, 'Cash'],
       [1005, '2025-10-03', 'Ryou M', 'Mobile Phone', 'Electronics', 1,
        22000, '8%', 22000, 20240, 'Net Banking']], dtype=object)

In [ ]:
data[:,6]

array([55000, 600, 32000, 2500, 22000], dtype=object)

In [ ]:
data[:,6].sum()

112100

In [ ]:
data[:,5].argmax()+1

np.int64(2)

In [ ]:
(data[:,6]/data[:,5]).argmax()+1

np.int64(1)

In [ ]:
###Boardcasting in numpy

import numpy as np
x = np.random.randint(0,10,(3,3))
y = np.random.randint(0,10,(3,1)) ## scalar
print(x)
print(y)

[[8 0 8]
 [9 1 4]
 [4 0 1]]
[[8]
 [8]
 [9]]


In [ ]:
print(x+y)

[[13  9  9]
 [ 9  8 14]
 [13 12 12]]


In [ ]:
import math
np.log(math.pow(2.71823,0.234))

np.float64(0.233995538367321)

In [ ]:
data1=np.random.randint(0,10,(3,3))
data2=np.random.randint(0,10,(3,3))
print(data1)
print(data2)

[[3 9 0]
 [0 4 3]
 [8 6 1]]
[[0 9 5]
 [0 5 3]
 [0 8 1]]


In [ ]:
data1+data2

array([[ 3, 18,  5],
       [ 0,  9,  6],
       [ 8, 14,  2]])

In [ ]:
np.add(data1,data2)

array([[ 3, 18,  5],
       [ 0,  9,  6],
       [ 8, 14,  2]])

In [ ]:
np.subtract(data1,data2)

array([[ 3,  0, -5],
       [ 0, -1,  0],
       [ 8, -2,  0]])

In [ ]:
np.multiply(data1,data2)

array([[ 0, 81,  0],
       [ 0, 20,  9],
       [ 0, 48,  1]])

In [ ]:
np.divide(data1,data2)

/tmp/ipython-input-3065414091.py:1: RuntimeWarning: divide by zero encountered in divide
  np.divide(data1,data2)
/tmp/ipython-input-3065414091.py:1: RuntimeWarning: invalid value encountered in divide
  np.divide(data1,data2)


array([[ inf, 1.  , 0.  ],
       [ nan, 0.8 , 1.  ],
       [ inf, 0.75, 1.  ]])

In [ ]:
data1

array([[3, 9, 0],
       [0, 4, 3],
       [8, 6, 1]])

In [ ]:
data2

array([[0, 9, 5],
       [0, 5, 3],
       [0, 8, 1]])

In [ ]:
np.floor_divide(data1,data2)

/tmp/ipython-input-583036681.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.floor_divide(data1,data2)


array([[0, 1, 0],
       [0, 0, 1],
       [0, 0, 1]])

In [ ]:
#ceil function is used to round the value

data=np.random.randint(0,1,10)/5
print(data)
np.ceil(data)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
import numpy as np
data = np.random.randint(0,50,5)
print(data)


[27 26 21 41 40]


In [ ]:
data>5


array([ True,  True,  True,  True,  True])

In [ ]:
marks = np.random.randint(10,100,20)
print(marks)

[93 30 16 36 26 71 23 50 37 83 20 97 51 13 13 74 63 95 62 30]


In [ ]:
marks[marks>35]

array([93, 36, 71, 50, 37, 83, 97, 51, 74, 63, 95, 62])

In [ ]:
marks[marks<35]

array([30, 16, 26, 23, 20, 13, 13, 30])

In [ ]:
marks[marks<=np.mean(marks)] ## avergae

array([30, 16, 36, 26, 23, 37, 20, 13, 13, 30])

In [ ]:
###array manipulation

In [ ]:
data = np.random.randint(0,20,(3,3))
print(data)

[[10 11 13]
 [16  4 12]
 [ 8 17  0]]


In [ ]:
data.T ## T stands for traspose
       ## rows will become coloum,
       ## coloum will become rows


array([[10, 16,  8],
       [11,  4, 17],
       [13, 12,  0]])

In [ ]:
data = np.random.randint(0,20,(3,3))
print(data)
data.reshape(1,9)

[[ 9  3  0]
 [ 3  2 11]
 [ 0  6 12]]


array([[ 9,  3,  0,  3,  2, 11,  0,  6, 12]])

In [ ]:
np.hstack([data1,data2]) ## is a horizontal stack

array([[3, 9, 0, 0, 9, 5],
       [0, 4, 3, 0, 5, 3],
       [8, 6, 1, 0, 8, 1]])

In [ ]:
np.vstack([data1,data2])   #Vertical stack

array([[3, 9, 0],
       [0, 4, 3],
       [8, 6, 1],
       [0, 9, 5],
       [0, 5, 3],
       [0, 8, 1]])

In [ ]:
data = np.random.randint(0,10,10)## split it cannot work both equal values
np.split(data,2)

[array([9, 0, 5, 4, 7]), array([5, 3, 2, 8, 5])]

In [ ]:
matrix = np.array([[1,2,3,4],
                   [5,6,7,8 ]])
