<a href="https://colab.research.google.com/github/poolaNaveen/Data-Engineering/blob/main/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
# 2. Create a 3×3 matrix with values ranging from 2 to 10
arr2 = np.arange(2, 11).reshape(3, 3)
print("\nQ2:\n", arr2)



Q2:
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [13]:
# 3. Find the maximum, minimum, and mean of a NumPy array
arr3 = np.array([12, 45, 7, 23, 89, 34])
print("\nQ3: Max:", arr3.max(), " Min:", arr3.min(), " Mean:", arr3.mean())



Q3: Max: 89  Min: 7  Mean: 35.0


In [14]:
# 4. Create an array of 10 zeros and 10 ones
arr4 = np.concatenate([np.zeros(10), np.ones(10)])
print("\nQ4:", arr4)



Q4: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [11]:
import numpy as np

# 1. Create a NumPy array of numbers from 1 to 20
arr1 = np.arange(1, 21)
print("Q1:", arr1)


Q1: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [15]:
# 5. Generate an array of 100 random numbers between 0 and 1
arr5 = np.random.rand(100)
print("\nQ5:", arr5[:10], "... (first 10 shown)")


Q5: [0.35163116 0.43401273 0.68437207 0.22787154 0.41192175 0.90824407
 0.57661241 0.49851952 0.26441642 0.68786896] ... (first 10 shown)


In [16]:
# 6. Reshape a 1D array of 12 elements into a 3×4 matrix
arr6 = np.arange(1, 13).reshape(3, 4)
print("\nQ6:\n", arr6)


Q6:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
# 7. Extract all odd numbers from a NumPy array
arr7 = np.arange(1, 21)
odds = arr7[arr7 % 2 != 0]
print("\nQ7:", odds)


Q7: [ 1  3  5  7  9 11 13 15 17 19]


In [18]:
# 8. Replace all negative values in an array with 0
arr8 = np.array([2, -4, 6, -9, 12, -1])
arr8[arr8 < 0] = 0
print("\nQ8:", arr8)


Q8: [ 2  0  6  0 12  0]


In [19]:
# 9. Multiply two NumPy arrays element-wise
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("\nQ9:", a * b)


Q9: [ 4 10 18]


In [20]:
# 10. Find the index of the maximum element in an array
arr10 = np.array([10, 55, 32, 89, 40])
print("\nQ10: Index of max element =", arr10.argmax(), " Value =", arr10.max())


Q10: Index of max element = 3  Value = 89
